### ISSUE TITLE
Add KIP-51 support

### ISSUE THREAD

**Issue by andrewstevenson** [datamountaineer/kafka-connect-tools#1]
https://issues.apache.org/jira/browse/KAFKA-3316

**Comment by rollulus** [comment]
@andrewstevenson, what do you think: we now have the command: `ls` to list active connectors names. On the one hand, I'd say that with the new API endpoints `ls` could show _available_ connector names, and introduce `ps` to show  _active_ connectors. On the other hand, that breaks the current behaviour of the CLI, where `ls` lists _active_ connectors.

**Comment by andrewstevenson** [comment]
I think ps to show active and ls to show available inline with linux.

**Comment by rollulus** [comment]
Exactly, my thoughts too.
