### ISSUE TITLE
Properties parsing regex rejects valid properties

### ISSUE THREAD

**Issue by 56quarters** [datamountaineer/kafka-connect-tools#23]
Hi,

According to the [documentation](http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) for the Java `Properties` class, properties may be split over multiple lines. However, the regex currently used to parse these properties doesn't support this.

For example, this setting:

```
fields.whitelist=\
     id,\
     timestamp,\
     search_id
```

... should be parsed into the JSON

```json
{"fields.whitelist":"id,timestamp,search_id"}
```

But instead it is parsed into

```json
{"fields.whitelist":"\\"}
```

I'd like to propose changing the `ExecuteCommand.propsToMap` method to use the `Properties` class instead of a regex. If this is OK, I can submit a PR for this. Thanks!

**Comment by andrewstevenson** [comment]
@56quarters  PRs welcome!

**Comment by 56quarters** [comment]
Thanks, submitted!
